### ISSUE TITLE
Download file with absolute path

### ISSUE THREAD

**Issue by samuelwei** [mostafaznv/php-x-sendfile#2]
Hello,

thank you for this usefull package.
In the docs is says you can provide a relative and absolute path for the file (https://github.com/mostafaznv/php-x-sendfile#download)
However the file path is allways handled like a relative path: 

https://github.com/mostafaznv/php-x-sendfile/blob/4699f3dbc7e140cc0cd10d683ee4ebb252416451/src/PhpXsendfile.php#L49

https://github.com/mostafaznv/php-x-sendfile/blob/4699f3dbc7e140cc0cd10d683ee4ebb252416451/src/PhpXsendfile.php#L247-L250

**Comment by mostafaznv** [comment]
Hi @SamuelWei 

You can pass an absolute or relative path to the download method but this package works with absolute paths in its internal functions.


https://github.com/mostafaznv/php-x-sendfile/blob/4699f3dbc7e140cc0cd10d683ee4ebb252416451/src/PhpXsendfile.php#L241-L271

**Comment by kieranmetcalfe** [comment]
I'm hitting this issue too. 

In my situation (Laravel), the download files aren't in the web root, but in protected folders on a storage disk. So, to get the path of the file for download, I'm using

Storage::disk('file-store')->path($filename)

When passed into the download, it prepends the webroot to this path, and so fails.

How would I make this work with the library?

**Comment by kieranmetcalfe** [comment]
Ah - sorry - I've realised what's going on.

It appears x-litespeed-location must be relative to the doc root, so I needed to swap out the value of storage_path('') in my path with /../storage resulting in

/path/to/public_html/../storage/protected/file.zip

**Comment by mostafaznv** [comment]
Hi @SamuelWei 
Thanks for the report.

In Laravel, `$_SERVER['DOCUMENT_ROOT']` points to the public folder. so you should upload your files into the  public path.
But If you want to know my opinion about this situation, it's ugly 😁.
I will work on it soon.

**Comment by mostafaznv** [comment]
Hi again.
Please update to [v1.1.0](https://github.com/mostafaznv/php-x-sendfile/releases/tag/1.1.0)

------

it works under this conditions:

**Disk:**
```php
// config/filesystems.php

'file-store' => [
    'driver' => 'local',
    'root'   => storage_path('app/private')
],
``` 

**Config:**
```php
// config/x-sendfile.php

return [
    'server' => null,
    'base-path' => $_SERVER['DOCUMENT_ROOT'] . '/../',
    ...
];
``` 

**Nginx:**
```bash
location ^~ /storage/app/private/ {
        internal;
        alias /path/to/project/root/storage/app/private/;
}
```

**Route:**
```php
// routes/web.php

Route::get('/download', function() {
    $path = 'files/DX18DDrJXCh6TPehKR4CJSwN1cPQGua1Um5VJhvI.jpg';
    $path = Storage::disk('file-store')->path($path);

    PhpXsendfile::download($path);
    exit();
});
```
